# Generated by Django 5.0.2 on 2024-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0002_remove_user_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(to='client.client'),
        ),
    ]
