# Generated by Django 5.0.2 on 2024-03-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('start_time', models.DateTimeField(verbose_name='время старта рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='daily', max_length=10, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('finished', 'завершена'), ('created', 'создана'), ('started', 'запущена')], default='created', max_length=10, verbose_name='статус')),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_message.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
